apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mybookdeploy
  labels: 
   app: mybookdeploy
spec:
  replicas: 3  
  selector:   
    matchLabels:
     app: mybookdeploy
  template:
    metadata: 
      labels: 
        app: mybookdeploy
    spec:
      containers:
      - name: mybookdeploy
        image: nginx
        volumeMounts:
         - name: myvolume
           mountPath: /usr/share/nginx/html  
      volumes:
       - name: myvolume    
         PersistentVolumeClaim:
          claimName: my-nfs-claim   # nome do serviço pvc que foi criado 
        
