apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: bookdb
  labels: 
   app: bookdb
spec:
  replicas: 1
  selector:  
    matchLabels:
     app: bookdb
  template:
    metadata:  
      labels: 
        app: bookdb
    spec:
      containers:
      - name: book-service-db
        image: postgres:15
        envFrom:
         - secretRef:
            name: mysecret  # nome dado na criação da secret 


# tipos de secret
# docker-registry -> cria um secret para ser utilizado com docker registry
# generic -> cria uma secret local com um arquivo ou diretório 
# tls -> cria uma secret do tipo tls
# para criar uma secret no terminal : kubectl create secret generic mysecret --from-literal POSTGRES_USER=postgres --from-literal POSTGRES_PASSWORD=root --from-literal POSTGRES_DB=bookdb