apiVersion: v1
kind: PersistentVolume
metadata: 
  name: my-nfs-volume  # nome do serviço para diferenciar de outros 
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:  # as políticas de acesso são limitadas pelas capacidades do armazenamento subjacente (o driver de volume que você está usando, como AWS EBS, Azure Disk, etc.).
   - ReadWriteMany
  nfs:  # Indica ao Kubernetes que este volume persistente deve se conectar a um servidor usando o Network File System (NFS).
    path: /storage
    server: 192.168.1.20


#   TIPOS DE PERSISTENCIA DE VOLUME

#   persistentVolumeReclaimPolicy: Retain  ->  e seus dados após a exclusão da reivindicação de volume persistente (PVC). Em vez de ser excluído automaticamente, o PV é movido para o estado "Released", exigindo que um administrador exclua e limpe manualmente o volume para que ele possa ser usado novamente.
#   persistentVolumeReclaimPolicy: Delete  ->  esta política automatiza a limpeza, o que é o comportamento mais comum para volumes provisionados dinamicamente. O que acontece: Quando o usuário deleta o PersistentVolumeClaim (PVC), o Kubernetes deleta automaticamente o PersistentVolume (PV).
#   persistentVolumeReclaimPolicy: Recycle ->  Esta política foi depreciada (obsoleta) e deve ser evitada nas instalações atuais do Kubernetes. O que acontecia: Quando o PVC era deletado, o Kubernetes executava uma operação de limpeza básica (rm -rf /thevolume/*) no volume.

#   TIPOS DE POLITICA DE ACESSO   

#  ReadWriteMany (RWX) -> O volume pode ser montado para leitura e escrita (ReadWrite) por múltiplos Nodes (Nós) do cluster simultaneamente. acesso múltiplos Pods, rodando em diferentes máquinas (Nodes), podem acessar e modificar os dados ao mesmo tempo.
#  ReadWriteOnce (RWO) ->  O volume pode ser montado para leitura e escrita (ReadWrite) por um único Node (Nó) do cluster por vez.  Apenas um Node pode anexar o volume. No entanto, múltiplos Pods rodando naquele mesmo Node podem usar o volume.
#  ReadOnlyMany (ROX)  -> O volume pode ser montado para leitura (ReadOnly) por múltiplos Nodes (Nós) do cluster simultaneamente. Múltiplos Pods, rodando em diferentes Nodes, podem ler os dados ao mesmo tempo, mas nenhum Pod pode escrever.
#  ReadWriteOncePod (RWOP) -> O volume pode ser montado para leitura e escrita por um único Pod em todo o cluster. Diferença para RWO: O RWO restringe o acesso ao Node, permitindo que múltiplos Pods nesse Node usem o volume. O RWOP restringe o acesso ao Pod, garantindo que apenas um único Pod tenha acesso em todo o cluster, protegendo contra corrupção de dados se o Pod for movido para outro Node.
